#!/usr/bin/env bash
# Set up NGINX server with custom http header
sudo apt-get update
sudo apt- get -y install nginx
sudo sed -i "31i\ $\t\tadd_header X-Server-By '$HOSTNAME';"
sudo service nginx start
