#!/usr/bin/env bash
# prints Holerton School ten times
h=0
while [ $h -lt 13 ]
do 
    echo "Hour: $h"
    m=1
    while [ $m -le 59 ]
    do
        echo "$m"
        m=$((m + 1))
    done
    h=$((h + 1))
done
